# Generated by Django 2.1.4 on 2018-12-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='field',
        ),
    ]
